package gpsystem;

import javax.swing.*;
import java.awt.*;
import java.io.File;

public class gallery_dsb extends JFrame {

    private static final String IMAGE_DIR = "captures"; // Folder containing images
    private JButton openFolderButton;
    private JButton backButton;

    public gallery_dsb() {
        setTitle("Gallery - Open Folder");
        setSize(400, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        initializeComponents();
        setLocationRelativeTo(null);
    }

    private void initializeComponents() {
        JPanel panel = new JPanel(new GridLayout(2, 1, 10, 10));

        openFolderButton = new JButton("Open Gallery Folder");
        openFolderButton.addActionListener(e -> openGalleryFolder());

        backButton = new JButton("Back");
        backButton.addActionListener(e -> dispose()); // Closes the window

        panel.add(openFolderButton);
        panel.add(backButton);

        add(panel, BorderLayout.CENTER);
    }

    private void openGalleryFolder() {
        File directory = new File(IMAGE_DIR);
        if (!directory.exists() || !directory.isDirectory()) {
            JOptionPane.showMessageDialog(this, "Folder not found: " + IMAGE_DIR, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Desktop.getDesktop().open(directory);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to open folder!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar_dsb1 = new gpsystem.sidebar_dsb();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar_dsb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 584, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar_dsb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            gallery_dsb gallery = new gallery_dsb();
            gallery.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gpsystem.sidebar_dsb sidebar_dsb1;
    // End of variables declaration//GEN-END:variables
}
