package gpsystem;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author predator 300
 */
public class sidebar_dsb extends javax.swing.JPanel {

    private List<JFrame> openFrames;
    /**
     * Creates new form sidebar_dsb
     */
    public sidebar_dsb() {
        initComponents();
        setOpaque(false);
        openFrames = new ArrayList<>();
    }
    
    public void addFrame(JFrame frame) {
        openFrames.add(frame);
    }
        
    private void closeAllFrames() {
        for (JFrame frame : openFrames) {
            if (frame != null) {
                frame.dispose();
            }
        }
        openFrames.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        homeBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        galleryBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 102));

        homeBtn.setFont(new java.awt.Font("Helvetica", 1, 25)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setText("HOME");
        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeBtn.setMaximumSize(new java.awt.Dimension(68, 23));
        homeBtn.setMinimumSize(new java.awt.Dimension(68, 23));
        homeBtn.setRequestFocusEnabled(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        processBtn.setFont(new java.awt.Font("Helvetica", 1, 25)); // NOI18N
        processBtn.setForeground(new java.awt.Color(255, 255, 255));
        processBtn.setText("PROCESS");
        processBtn.setBorder(null);
        processBtn.setBorderPainted(false);
        processBtn.setContentAreaFilled(false);
        processBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        processBtn.setMaximumSize(new java.awt.Dimension(68, 23));
        processBtn.setMinimumSize(new java.awt.Dimension(68, 23));
        processBtn.setRequestFocusEnabled(false);
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        galleryBtn.setFont(new java.awt.Font("Helvetica", 1, 25)); // NOI18N
        galleryBtn.setForeground(new java.awt.Color(255, 255, 255));
        galleryBtn.setText("GALLERY");
        galleryBtn.setBorder(null);
        galleryBtn.setBorderPainted(false);
        galleryBtn.setContentAreaFilled(false);
        galleryBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        galleryBtn.setMaximumSize(new java.awt.Dimension(68, 23));
        galleryBtn.setMinimumSize(new java.awt.Dimension(68, 23));
        galleryBtn.setRequestFocusEnabled(false);
        galleryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galleryBtnActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Helvetica", 1, 25)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BTN4");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setMaximumSize(new java.awt.Dimension(68, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(68, 23));
        jButton4.setRequestFocusEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(homeBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(processBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(galleryBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(galleryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(processBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(galleryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        processBtn.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
//        JOptionPane.showMessageDialog(this, "\"Home\" Is Pressed");
        closeAllFrames(); // Close all open frames
        JFrame currentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (currentFrame != null) {
            currentFrame.dispose();
        }
        home_dsb home = new home_dsb(); // Create a new home_dsb frame
        home.setVisible(true); // Set the new frame to visible
        openFrames.add(home); // Add the new frame to the list of open frames
//          new home_dsb().setVisible(true);
//          this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
//        JOptionPane.showMessageDialog(this, "\"RFQ\" Is Pressed");
        closeAllFrames(); // Close all open frames
        JFrame currentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (currentFrame != null) {
            currentFrame.dispose();
        }
        preprocess_dsb preprocess_dsb = new preprocess_dsb(); // Create a new RFQ_dsb frame
        preprocess_dsb.setVisible(true); // Set the new frame to visible
        openFrames.add(preprocess_dsb); // Add the new frame to the list of open frames
    }//GEN-LAST:event_processBtnActionPerformed

    private void galleryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galleryBtnActionPerformed
//        closeAllFrames(); // Close all open frames
//        JFrame currentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
//        if (currentFrame != null) {
//            currentFrame.dispose();
//        }
//
//        // Open the default file explorer at a specific directory
//        try {
//            File directory = new File("C:\\Users\\YourUsername\\Documents"); // Replace with your desired directory path
//            if (!directory.exists()) {
//                System.out.println("Directory does not exist: " + directory.getAbsolutePath());
//                return;
//            }
//            Desktop desktop = Desktop.getDesktop();
//            desktop.open(directory);
//        } catch (IOException e) {
//            e.printStackTrace();
//            System.out.println("An error occurred while trying to open the file explorer.");
//        }

            closeAllFrames(); // Close all open frames
            JFrame currentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            if (currentFrame != null) {
                currentFrame.dispose();
            }

            // Open the Embedded File Explorer
            SwingUtilities.invokeLater(() -> new EmbeddedImageExplorer());
//        gallery_dsb gallery_dsb = new bidding_dsb(); // Create a new bidding_dsb frame
//        gallery_dsb.setVisible(true); // Set the new frame to visible
//        openFrames.add(gallery_dsb); // Add the new frame to the list of open frames   
    }//GEN-LAST:event_galleryBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        closeAllFrames();
        JFrame currentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (currentFrame != null) {
            currentFrame.dispose();
        }
        JOptionPane.showMessageDialog(this, "\"Btn4\" Is Pressed");
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton galleryBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JButton processBtn;
    // End of variables declaration//GEN-END:variables
}
